// seedkernel-shell — the NODE platform (README §12).
//
// `boot()` assembles a node out of this platform's parts — `NodeFs` on a data directory, a
// `node:net` channel factory, a file-backed freshness store — and hands them to the shared
// `createShell`. It knows nothing about any app: everything arrives as a signed bundle
// (§12.4) whose author must clear the policy gate.
//
// The operator's side — flags, defaults, boot sequence, console lines — is `cli.ts`, which
// every target runs; `main-node.ts` binds it to this platform.
import { readFileSync, writeFileSync, renameSync } from "node:fs";
import { loadCrypto } from "./crypto-node.js";
import { policyFromJson } from "./policy.js";
import { FreshnessMarks, freshnessPathFor, type LoadedBundle } from "./bundle.js";
import { NodeChannelFactory } from "./net-node.js";
import { NodeFs } from "./fs-node.js";
import { fromBase64 } from "../core/util.js";
import { createShell, ModuleTable, isAdmissionRejected, type RealmFactory, type Shell as CoreShell, type ShellSodium } from "./shell-core.js";
// The transport bundle the artifact ships (§12.6), generated by
// scripts/build-transport-bundle.mjs: loading it is what stands the node's network up.
import { TRANSPORT_BUNDLE_B64 } from "./transport-bundle.js";
import { type ChannelFactory } from "../core/socket-seam.js";
import type { Keypair } from "../core/subkeys.js";
import { type PeerId } from "../core/socket-seam.js";
import { type Fs } from "../core/fs.js";
import { NET_PROTOCOL } from "../core/domains.js";
import { TransportHost } from "./transport-host.js";
import type { NodeRuntime as CliNodeRuntime } from "./cli.js";

export interface ShellOptions {
    /** Policy file contents (policy.ts). Omit ⇒ deny-all: the node boots and serves but
     *  accepts no installs. */
    policyJson?: string;
    /** Directory backing the fs.* capability. */
    dir: string;
    /** This node's keypair (README §12.6) — the derived channel keypair, whose public
     *  half is the peer id and the node's one identity (§12.9). */
    identity: Keypair;
    /** Optional deployment secret (§12.6.3). */
    contactSecret?: Uint8Array;
    listen?: {
        host: string;
        port: number;
    };
    wsListen?: {
        host: string;
        port: number;
    };
    /** Optional network key — which network this node belongs to (an isolation
     *  boundary, not a gate; §12.6). Absent ⇒ the public network. */
    networkKey?: Uint8Array;
    /** The socket seam the transport driver dials and listens through. Defaults to
     *  a NodeChannelFactory on listen/wsListen. */
    channels?: ChannelFactory;
    /** The signed transport bundle blob, defaulting to the artifact's own. The policy must
     *  grant its author the `link` privilege (never the plain `authors` list); a shell
     *  without an admitted transport bundle has no network. */
    transportBundle?: Uint8Array;
    /** Default per-request deadline in ms — how long one net request may take before
     *  it settles as unreachable, for a caller that names none of its own (§12.6). */
    requestDeadlineMs?: number;
    /** Budget of guest *execution* time per entrypoint invocation, in ms (§12.3). Counts
     *  time the guest is running, not time parked on a host seam, so it bounds a wedged
     *  guest without penalising one awaiting the network. `Infinity` disables it. Threaded
     *  through to `createShell` because a bound no target can set is a bound nobody has. */
    guestDeadlineMs?: number;
    /** QuickJS heap cap for the guest realm, in bytes (§12.3). Omitted ⇒ the 64 MiB
     *  default. Raise it for an app that streams large windows through the guest. */
    realmMemoryBytes?: number;
    /** Operator-supplied app config, merged *over* the bundle manifest's `config` into the
     *  guest's `const APP = …`: per-node operator settings (a storage node's `quota`), as
     *  opposed to the author-signed structural constants. Opaque to the runtime. */
    config?: Record<string, string | number>;
}

/** The Node-side Shell — the platform-neutral CoreShell plus a file-backed
 *  `loadBundle` and a guaranteed `fs` (Node always has a filesystem). */
export interface Shell extends CoreShell {
    fs: Fs;
    /** Load a signed bundle *file*: read it from disk then delegate to
     *  loadBundleBlob (§12.4). This is the Node convenience wrapper;
     *  cross-platform callers use loadBundleBlob directly. */
    loadBundle(file: string): Promise<LoadedBundle>;
}

/** The CLI's runtime pair, narrowed to this platform's shell — one declaration of the
 *  shape, so `standUp` returning it stays a compile-time fact rather than a coincidence. */
export interface NodeRuntime extends CliNodeRuntime {
    shell: Shell;
}

/** A `FreshnessStore` backed by one JSON file (`{ marks, revoked }`), kept OUTSIDE the
 *  guest-writable fs directory so a `fs`-capable guest cannot tamper with its own mark or
 *  the dead-key set beside it (§12.5). An operator rolls back a mark, or un-revokes a key,
 *  by editing this file out of band. The rules live in `FreshnessMarks` (bundle.ts); this
 *  adds only the Node persistence seam. */
export class FileFreshnessStore extends FreshnessMarks {
    path;
    constructor(path: string) {
        let json = null;
        try {
            json = readFileSync(path, "utf8");
        }
        catch { /* absent/unreadable ⇒ start empty (−∞ for every key) */ }
        super(json);
        this.path = path;
    }
    persist(json: string): void {
        // Temp + rename, because a bare writeFileSync truncates in place: a crash mid-write
        // leaves truncated JSON, which the constructor reads as "start empty" — every
        // downgrade mark silently discarded on the next boot (§12.4).
        const tmp = `${this.path}.${process.pid}.tmp`;
        writeFileSync(tmp, json);
        renameSync(tmp, this.path);
    }
}
/** The JS platform's realm factory (§12.3): safe-js, a QuickJS interpreter compiled to
 *  wasm. Imported lazily — the engine is heavy and a node that never runs a guest should
 *  not pay for it, which is why realm creation is a platform member rather than something
 *  the shared shell reaches for itself. */
const createRealm: RealmFactory = async (o) => (await import("./safe-js.js")).createSafeRealm(o);
/** Assemble the runtime on Node: build the platform seam, hand it to `createShell`, then
 *  load the transport bundle — the signed program that IS the node's network. */
export async function bootRuntime(opts: ShellOptions): Promise<NodeRuntime> {
    const sodium = await loadCrypto();
    // ── Node platform seam ─────────────────────────────────────────────────────
    const fs = new NodeFs(opts.dir);
    const freshness = new FileFreshnessStore(freshnessPathFor(opts.dir));
    const channels = opts.channels ?? new NodeChannelFactory();
    const transport = new TransportHost({
        identity: opts.identity,
        networkKey: opts.networkKey,
        contactSecret: opts.contactSecret,
        requestDeadlineMs: opts.requestDeadlineMs,
        channels,
        listen: opts.listen,
        wsListen: opts.wsListen,
    });
    // Everything below can fail — a bundle that does not verify, a listener whose port is
    // taken — and a boot that throws returns no handle, so whatever it stood up would be
    // unreachable and unclosable for the process's life: a bound socket and an open
    // channel factory with nobody left to close them. One teardown, swapped for the
    // shell's as soon as there IS a shell, since `core.close()` disposes the realms and
    // the adapter both.
    let undo = () => transport.close();
    try {
        // ── Assemble the shared shell ───────────────────────────────────────────
        const policy = policyFromJson(opts.policyJson);
        const core = createShell({
            platform: {
                sodium: sodium as unknown as ShellSodium, identity: opts.identity,
                table: new ModuleTable(), fs, freshnessStore: freshness,
                networkKey: opts.networkKey, transportHost: transport,
                createRealm,
            },
            admit: policy,
            guestDeadlineMs: opts.guestDeadlineMs,
            realmMemoryBytes: opts.realmMemoryBytes,
            config: opts.config,
        });
        undo = () => core.close();
        // ── Load the transport bundle: the node's network (§12.6) ───────────────
        // The ONE install path, like any other bundle: verify, govern under policy, install,
        // and — because it reaches `link` — stand the driver up. A policy that does not admit
        // the transport author leaves the node without a network, which is a deliberate
        // configuration rather than an error.
        if (opts.transportBundle ?? EMBEDDED_TRANSPORT) {
            try {
                await core.loadBundleBlob(opts.transportBundle ?? EMBEDDED_TRANSPORT!);
            }
            catch (err) {
                if (isAdmissionRejected(err)) {
                    console.warn('  no transport: the policy grants "link" to no author of this bundle');
                }
                else {
                    throw err;
                }
            }
        }
        // The adapter is host integration state. Binding its listeners does not put it on
        // the shell, and only happens when an ordinary bundle currently claims `_net`.
        if (core.resolve(NET_PROTOCOL)) await transport.start();
        // ── Node wrapper: add file-backed loadBundle ────────────────────────────
        const shell: Shell = {
            host: core.host,
            resolve: core.resolve,
            routes: core.routes,
            // boot() always supplies an fs (Node always has a filesystem), so the optional
            // seam member is non-null here.
            fs: core.fs!,
            sodium: core.sodium,
            loadBundleBlob: core.loadBundleBlob,
            uninstall: core.uninstall,
            revoke: core.revoke,
            async loadBundle(file) {
                return core.loadBundleBlob(new Uint8Array(readFileSync(file)));
            },
            invoke: core.invoke,
            dispatch: core.dispatch,
            close() { core.close(); },
        };
        return { shell, transport };
    }
    catch (err) {
        undo();
        throw err;
    }
}

/** Assemble a Node shell. Callers that also operate the concrete channel adapter use
 *  {@link bootRuntime}; ordinary shell callers do not receive host integration state. */
export async function boot(opts: ShellOptions): Promise<Shell> {
    return (await bootRuntime(opts)).shell;
}
/** The artifact-shipped transport bundle, as raw bytes (transport-bundle.ts). */
const EMBEDDED_TRANSPORT = (() => {
    try {
        return fromBase64(TRANSPORT_BUNDLE_B64);
    }
    catch {
        return null;
    }
})();
// Re-exported so callers get everything from one import.
export { createShell } from "./shell-core.js";
