// seedkernel-shell — the generic runtime entry (README §12).
// It stands up the handler table under an install policy and serves; it knows
// nothing about storage or any other app. Everything an app needs arrives as a signed bundle
// (§12.4) whose manifest author must clear the --policy gate. The runtime offers
// raw-byte capabilities — crypto (the bundled sumo), fs.* on --dir, net.* on
// --listen — and the safe-js confinement host, wired to a bundle's declared cap
// domains when one loads (§12.4); the kernel itself stays application-neutral.
//
//   node build/host/main-node.js --policy ./allowed-keys.json --dir ./data \
//        --listen 0.0.0.0:7000 --bundle ./app.skb
//
// A loaded guest runs under two operator-set resource bounds (§12.3), both defaulted:
// --guest-timeout <ms> (execution budget per entrypoint call, default 5000; 0 = none)
// and --guest-memory <MiB> (realm heap cap, default 64).
//
// For a self-contained non-browser binary, the Go/native target (native/,
// README §12.9) embeds and runs this same shared host JS — no Node install needed.
import { readFileSync, writeFileSync, renameSync, existsSync } from "node:fs";
import { resolve } from "node:path";
import { loadSodium } from "./node.js";
import { policyFromJson } from "./policy.js";
import { FreshnessMarks, type LoadedBundle } from "./bundle.js";
import { NodeChannelFactory, parsePeerSpec } from "./net-node.js";
import { NodeFs } from "./fs-node.js";
import { toHex, fromHex, concatBytes } from "../core/util.js";
import { deriveNodeKeys, type SubkeyCrypto, type NodeKeys } from "../core/subkeys.js";
type Sodium = Awaited<ReturnType<typeof loadSodium>>;
import { createShell, KernelHost, type RealmFactory, type Shell as CoreShell, type KernelTable, type ShellSodium } from "./shell-core.js";
import { TransportHost } from "./transport-host.js";
// The transport bundle the artifact ships (§12.6):
// generated by scripts/build-transport-bundle.mjs, signed by the seed transport
// author (see its header). Loading it is what stands the node's network up; an
// operator who pins a different transport author in policy builds their own.
import { TRANSPORT_BUNDLE_B64 } from "./transport-bundle.js";
import { type ChannelFactory, type Identity } from "../core/socket-seam.js";
import { type PeerId } from "../core/net.js";
import { type Fs } from "../core/fs.js";

export interface ShellOptions {
    /** allowed-keys.json contents (see policy.ts). Omit ⇒ a deny-all policy (no
     *  authors), so the node boots and serves but accepts no installs — handy for
     *  just bringing a node online (e.g. to test connectivity). */
    policyJson?: string;
    /** Directory backing the fs.* capability. */
    dir: string;
    /** This node's kernel keypair (README §12.6) — the CHANNEL subkey, whose public half
     *  is the peer id. */
    identity: Identity;
    /** The GUEST signing keypair (§12.9) — a sibling subkey of `identity`, used only by
     *  the cap-bridge SIGN op. Separate so guest signing structurally cannot produce a
     *  channel handshake signature, whatever happens to the domain prefixes. Defaults to
     *  `identity`, so an embedding host that supplies one keypair still works. */
    guestIdentity?: Identity;
    /** Optional deployment secret (§12.6.3). */
    contactSecret?: Uint8Array;
    listen?: {
        host: string;
        port: number;
    };
    wsListen?: {
        host: string;
        port: number;
    };
    /** Optional network key — which network this node belongs to (an isolation
     *  boundary, not a gate; §12.6). Absent ⇒ the public network. */
    networkKey?: Uint8Array;
    /** The socket seam the transport driver dials and listens through. Defaults to
     *  a NodeChannelFactory on listen/wsListen. */
    channels?: ChannelFactory;
    /** The signed transport bundle blob. Defaults to the one shipped in the
     *  artifact (transport-bundle.ts); the operator's policy must admit its author
     *  for the transport role. A shell without an admitted transport bundle has no
     *  network. */
    transportBundle?: Uint8Array;
    /** Live connected peers for the NET_PEERS cap. The transport owns
     *  connectivity; this closure feeds it into the cap-bridge. */
    livePeers?: () => PeerId[];
    /** Default per-request deadline in ms — how long one net request may take before
     *  it settles as unreachable, for a caller that names none of its own (§12.6). */
    requestDeadlineMs?: number;
    /** Budget of guest *execution* time per entrypoint invocation, in ms (§12.3, §16.1).
     *  Omitted ⇒ the 5s default. Counts time the guest is running, not time it spends
     *  parked on a host bridge, so it bounds a wedged guest without penalising one
     *  legitimately awaiting the network. `Infinity` disables it.
     *
     *  Reaching `createShell` from here is the point: a bound the shell accepts but no
     *  target can set is a bound nobody has — which is exactly what happened to
     *  safe-js's `deadlineMs` before this. */
    guestDeadlineMs?: number;
    /** QuickJS heap cap for the guest realm, in bytes (§12.3). Omitted ⇒ the 64 MiB
     *  default. Raise it for an app that streams large windows through the guest. */
    realmMemoryBytes?: number;
    /** Operator-supplied app config, merged *over* the bundle manifest's `config`
     *  into the guest's `const APP = …`. This is where per-node operator policy
     *  lives — e.g. a storage node's `quota` byte budget — as opposed to the
     *  author-signed manifest, which carries only content-structural constants
     *  (k/m/blockSize…). Opaque to the runtime: the shell merges two maps and never
     *  inspects a key, so it stays application-neutral. */
    config?: Record<string, string | number>;
}

/** The Node-side Shell — the platform-neutral CoreShell plus a file-backed
 *  `loadBundle` and a guaranteed `fs` (Node always has a filesystem). */
export interface Shell extends CoreShell {
    fs: Fs;
    /** Load a signed bundle *file*: read it from disk then delegate to
     *  loadBundleBlob (§12.4). This is the Node convenience wrapper;
     *  cross-platform callers use loadBundleBlob directly. */
    loadBundle(file: string): Promise<LoadedBundle>;
}

/** A `FreshnessStore` backed by one JSON file (`{ marks, revoked }`). Kept
 *  *outside* the guest-writable fs directory (a sibling file), so a `fs`-capable guest
 *  cannot tamper with its own freshness mark — or with the dead-key set beside it
 *  (§12.5). An operator rolls back a mark, or un-revokes a key, by editing this file
 *  out of band (the operator is the TCB, README §14).
 *
 *  The monotonic rule and the serialization live in `FreshnessMarks` (bundle.ts) —
 *  this adds only the Node persistence seam. */
export class FileFreshnessStore extends FreshnessMarks {
    path;
    constructor(path: string) {
        let json = null;
        try {
            json = readFileSync(path, "utf8");
        }
        catch { /* absent/unreadable ⇒ start empty (−∞ for every key) */ }
        super(json);
        this.path = path;
    }
    persist(json: string): void {
        // Persist atomically: write a sibling temp then rename onto the path (atomic within
        // a directory on POSIX; ReplaceFile semantics on Windows). A bare writeFileSync
        // truncates the file in place, so a crash mid-write could leave truncated JSON — which
        // the constructor's catch would silently read as "start empty", discarding the entire
        // downgrade-protection mark set on the next boot (README §12.4). Rename swaps the whole
        // file in one step, so a reader only ever sees the old or the complete new contents.
        const tmp = `${this.path}.${process.pid}.tmp`;
        writeFileSync(tmp, json);
        renameSync(tmp, this.path);
    }
}
/** The freshness file for a data directory: a sibling of the dir, so it can never
 *  collide with or be clobbered by a guest fs key (which is a file *inside* the dir). */
function freshnessPathFor(dir: string) {
    return resolve(dir).replace(/[/\\]+$/, "") + ".freshness.json";
}
/** The JS platform's realm factory (§12.3): safe-js, a QuickJS interpreter compiled
 *  to wasm. Imported lazily — the engine is a heavy module with bare-specifier
 *  imports, and a node that never runs a guest should never pay for it — which is
 *  exactly why realm creation is a platform member rather than something the shared
 *  shell reaches for itself. */
const createRealm: RealmFactory = async (o) => (await import("./safe-js.js")).createSafeRealm(o);
/** Assemble the runtime on Node: create the Node platform (NodeFs, FileFreshnessStore,
 *  the node:net channel factory) and hand it to the shared createShell(), then load
 *  the transport bundle — the signed program that IS the node's network. The Node
 *  shell is the platform-neutral core plus a file-backed `loadBundle` — that is the
 *  whole platform seam. */
export async function boot(opts: ShellOptions): Promise<Shell> {
    const sodium = await loadSodium();
    // ── Node platform seam ─────────────────────────────────────────────────────
    const fs = new NodeFs(opts.dir);
    const freshness = new FileFreshnessStore(freshnessPathFor(opts.dir));
    const channels = opts.channels ?? new NodeChannelFactory();
    // ── Assemble the shared shell ───────────────────────────────────────────────
    const core = createShell({
        platform: {
            sodium: sodium as unknown as ShellSodium, identity: opts.identity,
            guestIdentity: opts.guestIdentity,
            kernel: new KernelHost(), fs, freshnessStore: freshness,
            channels, listen: opts.listen, wsListen: opts.wsListen,
            contactSecret: opts.contactSecret, networkKey: opts.networkKey,
            createRealm, livePeers: opts.livePeers,
        },
        admit: policyFromJson(opts.policyJson),
        requestDeadlineMs: opts.requestDeadlineMs,
        guestDeadlineMs: opts.guestDeadlineMs,
        realmMemoryBytes: opts.realmMemoryBytes,
        config: opts.config,
    });
    // ── Load the transport bundle: the node's network (§12.6) ───────────────────
    // The ONE install path, like any other bundle: verify, govern under policy
    // (roles.transport), install, and — because it claims the transport role —
    // stand the driver up. A policy that does not admit the transport author
    // leaves the node without a network, which is a deliberate configuration
    // ("this node does not speak to anyone"), not an error.
    if (opts.transportBundle ?? EMBEDDED_TRANSPORT) {
        try {
            await core.loadBundleBlob(opts.transportBundle ?? EMBEDDED_TRANSPORT!);
        }
        catch (err) {
            if ((err as Error).message.includes("rejected by admission predicate")) {
                console.warn("  no transport: the policy does not admit a bundle for the transport role");
            }
            else {
                throw err;
            }
        }
    }
    const net = core.net;
    if (net instanceof TransportHost)
        await net.start();
    // ── Node wrapper: add file-backed loadBundle ───────────────────────────────
    return {
        host: core.host,
        bindings: core.bindings,
        net: core.net,
        transport: core.transport,
        fs: core.fs!,
        sodium: core.sodium,
        loadBundleBlob: core.loadBundleBlob,
        uninstall: core.uninstall,
        revoke: core.revoke,
        async loadBundle(file) {
            return core.loadBundleBlob(new Uint8Array(readFileSync(file)));
        },
        runGuest: core.runGuest,
        dispatch: core.dispatch,
        serve: core.serve,
        close() { core.close(); channels.close(); },
    };
}
/** The artifact-shipped transport bundle, as raw bytes (transport-bundle.ts). */
const EMBEDDED_TRANSPORT = (() => {
    try {
        const bin = atob(TRANSPORT_BUNDLE_B64);
        const out = new Uint8Array(bin.length);
        for (let i = 0; i < bin.length; i++)
            out[i] = bin.charCodeAt(i);
        return out;
    }
    catch {
        return null;
    }
})();
// Re-export the shared types so callers get everything from one import.
export { createShell } from "./shell-core.js";
interface Args { [k: string]: string | boolean }
function parseArgs(argv: string[]): Args {
    const out: Args = {};
    for (let i = 0; i < argv.length; i++) {
        const a = argv[i];
        if (!a.startsWith("--"))
            continue;
        const key = a.slice(2);
        const next = argv[i + 1];
        if (next === undefined || next.startsWith("--"))
            out[key] = true;
        else {
            out[key] = next;
            i++;
        }
    }
    return out;
}
function str(a: Args, k: string, def?: string): string | undefined {
    const v = a[k];
    return typeof v === "string" ? v : def;
}
function parseHostPort(s: string) {
    const colon = s.lastIndexOf(":");
    if (colon < 0)
        throw new Error(`expected host:port, got ${s}`);
    const host = s.slice(0, colon) || "0.0.0.0";
    const port = Number(s.slice(colon + 1));
    if (!Number.isInteger(port) || port < 0)
        throw new Error(`bad port in ${s}`);
    return { host, port };
}
/** Load the node's MASTER SEED from --key, or mint one and persist it, and derive every
 *  purpose-bound keypair from it (§12.9).
 *
 *  One secret on disk, 32 bytes. The master signs nothing itself — it only derives — so
 *  the channel handshake and guest SIGN hold different keys and neither can produce a
 *  signature for the other's purpose. Preimages are still domain-separated; separate keys
 *  make cross-purpose forgery structurally impossible rather than merely incorrect.
 *
 *  The node's peer id is the CHANNEL subkey's public half. */
function loadNodeKeys(sodium: Sodium, keyPath: string): NodeKeys {
    if (existsSync(keyPath)) {
        const master = fromHex(readFileSync(keyPath, "utf8").trim());
        if (master.length !== 32)
            throw new Error(`--key must hold a 32-byte master seed (got ${master.length})`);
        return deriveNodeKeys(sodium, master);
    }
    const master = sodium.randombytes_buf(32);
    writeFileSync(keyPath, toHex(master), { mode: 0o600 });
    return deriveNodeKeys(sodium, master);
}
/** Load the optional deployment secret from --contact-secret (a file holding 32 bytes of hex).
 *
 *  Omitting it is the DEFAULT and does not weaken identity concealment: with four
 *  messages the caller names itself before the receiver does, so a caller the receiver
 *  declines learns nothing either way, and both identities ride the ephemeral-ephemeral
 *  secret regardless. What the contact secret adds is a cheap gate in front of the responder's
 *  keypair — so a stranger costs one AEAD open rather than a keygen and a scalarmult —
 *  plus protection of the CALLER's identity against an active attacker who is not a
 *  member. It costs one secret shared by the whole deployment, which a single compromised
 *  node discloses for everyone, so it is opt-in. See §12.6.3. */
function loadContactSecret(path: string | undefined): Uint8Array | undefined {
    if (!path)
        return undefined;
    const k = fromHex(readFileSync(path, "utf8").trim());
    if (k.length !== 32)
        throw new Error(`--contact-secret must hold 32 bytes of hex (got ${k.length})`);
    return k;
}
export async function main(): Promise<void> {
    const args = parseArgs(process.argv.slice(2));
    // --policy is optional: omit it for a deny-all node (boots + serves, no installs).
    const policyPath = str(args, "policy");
    const policyJson = policyPath ? readFileSync(policyPath, "utf8") : undefined;
    const dir = str(args, "dir", "./seedkernel-data");
    const keyPath = str(args, "key", "./seedkernel.key");
    const sodium = await loadSodium();
    const keys = loadNodeKeys(sodium, keyPath!);
    const identity = keys.channel;
    const contactSecret = loadContactSecret(str(args, "contact-secret"));
    // Operator-supplied app config (e.g. a storage node's quota), merged over the
    // bundle's author-signed config. Opaque JSON the shell forwards into `const APP`.
    const appConfig = args["app-config"]
        ? JSON.parse(readFileSync(str(args, "app-config")!, "utf8"))
        : undefined;
    const shell = await boot({
        policyJson, dir: dir!, identity, contactSecret,
        listen: args["listen"] ? parseHostPort(str(args, "listen")!) : undefined,
        wsListen: args["ws-listen"] ? parseHostPort(str(args, "ws-listen")!) : undefined,
        requestDeadlineMs: args["request-deadline"] ? Number(str(args, "request-deadline")!) : undefined,
        transportBundle: args["transport"]
            ? new Uint8Array(readFileSync(str(args, "transport")!))
            : undefined,
        // Guest resource bounds (§12.3). Both default to a real number, so omitting the
        // flags leaves the guest bounded rather than unbounded; these only widen or
        // tighten. `--guest-timeout 0` reads as Infinity — "no budget" said explicitly,
        // rather than reached by leaving a flag off.
        guestDeadlineMs: args["guest-timeout"]
            ? (Number(str(args, "guest-timeout")) || Infinity)
            : undefined,
        realmMemoryBytes: args["guest-memory"]
            ? Number(str(args, "guest-memory")) * 1024 * 1024
            : undefined,
        config: appConfig,
    });
    const nodeNet = shell.net as unknown as TransportHost;
    // Cohort peers the guest may reach: teach the transport their addresses so it
    // can dial them. The transport owns connectivity (§12.10). A policy that admits
    // no transport bundle leaves `shell.net` as a null face whose members throw
    // "no transport" — say what is wrong rather than surfacing a raw TypeError off
    // the fallback object's missing members.
    if (args["peers"]) {
        if (!(nodeNet instanceof TransportHost)) {
            throw new Error("shell: --peers given, but the policy admits no transport bundle — there is nothing to dial from");
        }
        for (const spec of str(args, "peers")!.split(",").map((s) => s.trim()).filter(Boolean)) {
            const { peerId, addr } = parsePeerSpec(spec, "tcp");
            nodeNet.addPeerAddr(peerId, addr);
        }
        await nodeNet.ready();
    }
    console.log(`seedkernel-shell ${toHex(identity.publicKey)}`);
    console.log(`  policy ${policyPath ?? "(none — installs disabled)"}`);
    console.log(`  store  ${dir} (fs.* backend)`);
    console.log(`  cohort ${args["peers"] ? (str(args, "peers")!.split(",").filter(Boolean).length) : 0} peer(s)`);
    if (nodeNet.port)
        console.log(`  tcp    listening on :${nodeNet.port}`);
    if (nodeNet.wsPort)
        console.log(`  ws     listening on :${nodeNet.wsPort}`);
    // Operator remedies (§12.5), applied BEFORE --bundle deliberately: a node booting
    // with both should never briefly install what it was told to refuse. --revoke is
    // the whole remedy for a compromised key (refuse + tear down); --uninstall is the
    // narrower one — drop an app without writing its author off.
    const list = (name: string) => args[name] ? str(args, name)!.split(",").map((s) => s.trim()).filter(Boolean) : [];
    for (const hex of list("revoke")) {
        const gone = shell.revoke(hex);
        console.log(`  revoke ${hex}${gone.length ? ` (uninstalled ${gone.length} app(s))` : ""}`);
    }
    for (const appKey of list("uninstall")) {
        console.log(`  uninstall ${appKey}${shell.uninstall(appKey) ? "" : " (nothing bound)"}`);
    }
    // A signed bundle from disk (the file-first path; relay delivery is the next
    // step). The shell verifies + governs it before anything lands.
    if (args["bundle"]) {
        const b = await shell.loadBundle(str(args, "bundle")!);
        console.log(`  bundle ${b.manifest.app} v${b.manifest.version}`);
    }
    // One-shot client ops through the loaded guest — "the shell runs the app" as the
    // *initiator* (README §12.8). The request side is served below once we start
    // listening, from the same confined guest. The shell stays application-neutral:
    // arguments cross as raw bytes (a file for --put, hex tokens joined by ':' for
    // --get) and responses come back as raw bytes — any structure in them belongs to
    // the app, so the shell prints hex or writes them verbatim and never decodes.
    if (args["bundle"] && args["put"]) {
        const data = new Uint8Array(readFileSync(str(args, "put")!));
        const r = await shell.runGuest("put", data);
        console.log(`  PUT ok: ${r.length} B response`);
        console.log(`    ${toHex(r)}`);
    }
    if (args["bundle"] && args["get"]) {
        const arg = concatBytes(str(args, "get")!.split(":").map(fromHex));
        const data = await shell.runGuest("get", arg);
        const outFile = str(args, "out");
        if (outFile) {
            writeFileSync(outFile, data);
            console.log(`  GET ok: ${data.length} B → ${outFile}`);
        }
        else
            process.stdout.write(data);
    }
    const serving = !!(nodeNet.port || nodeNet.wsPort);
    if (!serving) {
        shell.close();
        return;
    }
    // A serving node with an app loaded also answers for the cohort: route incoming
    // requests to the app's confined request side, with no app-specific host code in
    // the runtime — the request types are the app's own (README §12.8).
    if (args["bundle"]) {
        await shell.serve();
        console.log("  serving the app's request side from the confined guest");
    }
    console.log("serving — Ctrl-C to stop");
    process.on("SIGINT", () => { shell.close(); process.exit(0); });
}
