// seedkernel-shell — the NODE platform (README §12).
//
// `boot()` below assembles a node out of this platform's parts — `NodeFs` on a data
// directory, a `node:net` channel factory, a file-backed freshness store — and hands
// them to the shared `createShell`. It knows nothing about storage or any other app:
// everything an app needs arrives as a signed bundle (§12.4) whose manifest author must
// clear the policy gate, and the runtime offers only raw-byte capabilities and the
// safe-js confinement host.
//
// The operator's side — flags, defaults, the boot sequence, the console lines — is NOT
// here. It is `cli.ts`, which every target runs, and `main-node.ts` binds it to this
// platform. For a self-contained non-browser binary, the Go/native target (native/,
// README §12.9) binds the same `cli.ts` to its own platform and needs no Node install.
import { readFileSync, writeFileSync, renameSync } from "node:fs";
import { loadCrypto } from "./crypto-node.js";
import { policyFromJson } from "./policy.js";
import { FreshnessMarks, freshnessPathFor, type LoadedBundle } from "./bundle.js";
import { NodeChannelFactory } from "./net-node.js";
import { NodeFs } from "./fs-node.js";
import { fromBase64 } from "../core/util.js";
import { createShell, ModuleTable, isAdmissionRejected, type RealmFactory, type Shell as CoreShell, type ShellSodium } from "./shell-core.js";
import { TransportHost } from "./transport-host.js";
// The transport bundle the artifact ships (§12.6):
// generated by scripts/build-transport-bundle.mjs, signed by the seed transport
// author (see its header). Loading it is what stands the node's network up; an
// operator who pins a different transport author in policy builds their own.
import { TRANSPORT_BUNDLE_B64 } from "./transport-bundle.js";
import { type ChannelFactory } from "../core/socket-seam.js";
import type { Keypair } from "../core/subkeys.js";
import { type PeerId } from "../core/net.js";
import { type Fs } from "../core/fs.js";

export interface ShellOptions {
    /** allowed-keys.json contents (see policy.ts). Omit ⇒ a deny-all policy (no
     *  authors), so the node boots and serves but accepts no installs — handy for
     *  just bringing a node online (e.g. to test connectivity). */
    policyJson?: string;
    /** Directory backing the fs.* capability. */
    dir: string;
    /** This node's node keypair (README §12.6) — the CHANNEL subkey, whose public half
     *  is the peer id. */
    identity: Keypair;
    /** The GUEST signing keypair (§12.9) — a sibling subkey of `identity`, used only by
     *  the seam's SIGN op. Separate so guest signing structurally cannot produce a
     *  channel handshake signature, whatever happens to the domain prefixes. Defaults to
     *  `identity`, so an embedding host that supplies one keypair still works. */
    guestIdentity?: Keypair;
    /** Optional deployment secret (§12.6.3). */
    contactSecret?: Uint8Array;
    listen?: {
        host: string;
        port: number;
    };
    wsListen?: {
        host: string;
        port: number;
    };
    /** Optional network key — which network this node belongs to (an isolation
     *  boundary, not a gate; §12.6). Absent ⇒ the public network. */
    networkKey?: Uint8Array;
    /** The socket seam the transport driver dials and listens through. Defaults to
     *  a NodeChannelFactory on listen/wsListen. */
    channels?: ChannelFactory;
    /** The signed transport bundle blob. Defaults to the one shipped in the
     *  artifact (transport-bundle.ts); the operator's policy must grant its author the
     *  `mount` privilege (never the plain `authors` list). A shell without an
     *  admitted transport bundle has no network. */
    transportBundle?: Uint8Array;
    /** Live connected peers for the net/peers name. The transport owns
     *  connectivity; this closure feeds it into the guest seam. */
    livePeers?: () => PeerId[];
    /** Default per-request deadline in ms — how long one net request may take before
     *  it settles as unreachable, for a caller that names none of its own (§12.6). */
    requestDeadlineMs?: number;
    /** Budget of guest *execution* time per entrypoint invocation, in ms (§12.3, §16.1).
     *  Omitted ⇒ the 5s default. Counts time the guest is running, not time it spends
     *  parked on a host seam, so it bounds a wedged guest without penalising one
     *  legitimately awaiting the network. `Infinity` disables it.
     *
     *  Reaching `createShell` from here is the point: a bound the shell accepts but no
     *  target can set is a bound nobody has — which is exactly what happened to
     *  safe-js's `deadlineMs` before this. */
    guestDeadlineMs?: number;
    /** QuickJS heap cap for the guest realm, in bytes (§12.3). Omitted ⇒ the 64 MiB
     *  default. Raise it for an app that streams large windows through the guest. */
    realmMemoryBytes?: number;
    /** Operator-supplied app config, merged *over* the bundle manifest's `config`
     *  into the guest's `const APP = …`. This is where per-node operator policy
     *  lives — e.g. a storage node's `quota` byte budget — as opposed to the
     *  author-signed manifest, which carries only content-structural constants
     *  (k/m/blockSize…). Opaque to the runtime: the shell merges two maps and never
     *  inspects a key, so it stays application-neutral. */
    config?: Record<string, string | number>;
}

/** The Node-side Shell — the platform-neutral CoreShell plus a file-backed
 *  `loadBundle` and a guaranteed `fs` (Node always has a filesystem). */
export interface Shell extends CoreShell {
    fs: Fs;
    /** Load a signed bundle *file*: read it from disk then delegate to
     *  loadBundleBlob (§12.4). This is the Node convenience wrapper;
     *  cross-platform callers use loadBundleBlob directly. */
    loadBundle(file: string): Promise<LoadedBundle>;
}

/** A `FreshnessStore` backed by one JSON file (`{ marks, revoked }`). Kept
 *  *outside* the guest-writable fs directory (a sibling file), so a `fs`-capable guest
 *  cannot tamper with its own freshness mark — or with the dead-key set beside it
 *  (§12.5). An operator rolls back a mark, or un-revokes a key, by editing this file
 *  out of band (the operator is the TCB, README §14).
 *
 *  The monotonic rule and the serialization live in `FreshnessMarks` (bundle.ts) —
 *  this adds only the Node persistence seam. */
export class FileFreshnessStore extends FreshnessMarks {
    path;
    constructor(path: string) {
        let json = null;
        try {
            json = readFileSync(path, "utf8");
        }
        catch { /* absent/unreadable ⇒ start empty (−∞ for every key) */ }
        super(json);
        this.path = path;
    }
    persist(json: string): void {
        // Persist atomically: write a sibling temp then rename onto the path (atomic within
        // a directory on POSIX; ReplaceFile semantics on Windows). A bare writeFileSync
        // truncates the file in place, so a crash mid-write could leave truncated JSON — which
        // the constructor's catch would silently read as "start empty", discarding the entire
        // downgrade-protection mark set on the next boot (README §12.4). Rename swaps the whole
        // file in one step, so a reader only ever sees the old or the complete new contents.
        const tmp = `${this.path}.${process.pid}.tmp`;
        writeFileSync(tmp, json);
        renameSync(tmp, this.path);
    }
}
/** The JS platform's realm factory (§12.3): safe-js, a QuickJS interpreter compiled
 *  to wasm. Imported lazily — the engine is a heavy module with bare-specifier
 *  imports, and a node that never runs a guest should never pay for it — which is
 *  exactly why realm creation is a platform member rather than something the shared
 *  shell reaches for itself. */
const createRealm: RealmFactory = async (o) => (await import("./safe-js.js")).createSafeRealm(o);
/** Assemble the runtime on Node: create the Node platform (NodeFs, FileFreshnessStore,
 *  the node:net channel factory) and hand it to the shared createShell(), then load
 *  the transport bundle — the signed program that IS the node's network. The Node
 *  shell is the platform-neutral core plus a file-backed `loadBundle` — that is the
 *  whole platform seam. */
export async function boot(opts: ShellOptions): Promise<Shell> {
    const sodium = await loadCrypto();
    // ── Node platform seam ─────────────────────────────────────────────────────
    const fs = new NodeFs(opts.dir);
    const freshness = new FileFreshnessStore(freshnessPathFor(opts.dir));
    const channels = opts.channels ?? new NodeChannelFactory();
    // ── Assemble the shared shell ───────────────────────────────────────────────
    const policy = policyFromJson(opts.policyJson);
    const core = createShell({
        platform: {
            sodium: sodium as unknown as ShellSodium, identity: opts.identity,
            guestIdentity: opts.guestIdentity,
            table: new ModuleTable(), fs, freshnessStore: freshness,
            channels, listen: opts.listen, wsListen: opts.wsListen,
            contactSecret: opts.contactSecret, networkKey: opts.networkKey,
            createRealm, livePeers: opts.livePeers,
        },
        admit: policy,
        requestDeadlineMs: opts.requestDeadlineMs,
        guestDeadlineMs: opts.guestDeadlineMs,
        realmMemoryBytes: opts.realmMemoryBytes,
        config: opts.config,
    });
    // ── Load the transport bundle: the node's network (§12.6) ───────────────────
    // The ONE install path, like any other bundle: verify, govern under policy, install,
    // and — because it requires the mount names — stand the driver up. A policy that
    // does not admit the transport author leaves the node without a network, which is a
    // deliberate configuration ("this node does not speak to anyone"), not an error.
    if (opts.transportBundle ?? EMBEDDED_TRANSPORT) {
        try {
            await core.loadBundleBlob(opts.transportBundle ?? EMBEDDED_TRANSPORT!);
        }
        catch (err) {
            if (isAdmissionRejected(err)) {
                console.warn('  no transport: the policy grants "mount" to no author of this bundle');
            }
            else {
                throw err;
            }
        }
    }
    const net = core.net;
    if (net instanceof TransportHost)
        await net.start();
    // ── Node wrapper: add file-backed loadBundle ───────────────────────────────
    return {
        host: core.host,
        resolve: core.resolve,
        routes: core.routes,
        net: core.net,
        transport: core.transport,
        // boot() always supplies an fs (Node always has a filesystem), so the optional
        // seam member is non-null here.
        fs: core.fs!,
        sodium: core.sodium,
        loadBundleBlob: core.loadBundleBlob,
        uninstall: core.uninstall,
        revoke: core.revoke,
        async loadBundle(file) {
            return core.loadBundleBlob(new Uint8Array(readFileSync(file)));
        },
        runGuest: core.runGuest,
        dispatch: core.dispatch,
        serve: core.serve,
        close() { core.close(); channels.close(); },
    };
}
/** The artifact-shipped transport bundle, as raw bytes (transport-bundle.ts). */
const EMBEDDED_TRANSPORT = (() => {
    try {
        return fromBase64(TRANSPORT_BUNDLE_B64);
    }
    catch {
        return null;
    }
})();
// Re-export the shared types so callers get everything from one import.
export { createShell } from "./shell-core.js";

// The operator flow that used to live here — argument parsing, the key file, the boot
// sequence, the console lines, --put/--get — moved to `cli.ts`, which every target now
// runs. It was duplicated in Go (`native/main.go`) and the two had drifted; this file
// keeps only what is genuinely the NODE platform: `boot()` over NodeFs, the Node
// channel factory, and a file-backed freshness store. `main-node.ts` binds `cli.ts`
// to this platform.
