// Inline build/ws.wasm into host/ws-wasm.ts as base64, so the host instantiates
// the no-cap WS codec synchronously at import with no fs read and no byte
// threading — which also means the Bun --compile binary carries it for free
// (README §13.7). The native WAMR engine loads the separate build/ws.wasm
// instead; both consume the same artifact.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const wasm = readFileSync(resolve(root, "build/ws.wasm"));
const b64 = wasm.toString("base64");

const out =
  "// GENERATED by scripts/inline-ws.mjs — do not edit.\n" +
  "// The no-cap ws.wasm (RFC 6455 framing + handshake) inlined as base64 so the\n" +
  "// host instantiates it synchronously at first use (README §13.1).\n" +
  `export const WS_WASM_B64 = ${JSON.stringify(b64)};\n`;

writeFileSync(resolve(root, "host/ws/ws-wasm.ts"), out);
console.log(`inlined ${wasm.length} B ws.wasm -> host/ws/ws-wasm.ts (${b64.length} b64 chars)`);
