"use strict";
// GENERATED by scripts/bundle-loader.mjs — do not edit.
(function () {

// ===== build/host/util.js =====
// Small byte helpers shared across the runtime host. No dependencies.
const HEX_BYTE = Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, "0"));
function toHex(b) {
    const out = new Array(b.length);
    for (let i = 0; i < b.length; i++)
        out[i] = HEX_BYTE[b[i]];
    return out.join("");
}
function fromHex(hex) {
    const out = new Uint8Array(hex.length >> 1);
    for (let i = 0; i < out.length; i++)
        out[i] = parseInt(hex.substr(i * 2, 2), 16);
    return out;
}
function bytesEqual(a, b) {
    if (a.length !== b.length)
        return false;
    for (let i = 0; i < a.length; i++)
        if (a[i] !== b[i])
            return false;
    return true;
}
function concatBytes(parts) {
    let total = 0;
    for (const p of parts)
        total += p.length;
    const out = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
        out.set(p, o);
        o += p.length;
    }
    return out;
}
function writeU32BE(out, offset, value) {
    out[offset] = (value >>> 24) & 0xff;
    out[offset + 1] = (value >>> 16) & 0xff;
    out[offset + 2] = (value >>> 8) & 0xff;
    out[offset + 3] = value & 0xff;
}
function readU32BE(buf, offset) {
    return ((buf[offset] << 24) | (buf[offset + 1] << 16) |
        (buf[offset + 2] << 8) | buf[offset + 3]) >>> 0;
}
/** A FIFO of bytes fed in arbitrary chunks. Receive paths use it so that
 *  accumulating a large message stays O(n): chunks are appended by reference and
 *  bytes are copied exactly once, when a complete record is taken out — instead
 *  of re-copying the whole buffer on every incoming chunk. */
class ByteQueue {
    chunks = [];
    head = 0; // read offset into chunks[0]
    size = 0;
    get length() { return this.size; }
    push(chunk) {
        if (chunk.length === 0)
            return;
        this.chunks.push(chunk);
        this.size += chunk.length;
    }
    /** Copy of the first n bytes without consuming them; null if fewer buffered. */
    peek(n) {
        if (n > this.size)
            return null;
        const out = new Uint8Array(n);
        let o = 0, head = this.head;
        for (let i = 0; o < n; i++) {
            const c = this.chunks[i];
            const take = Math.min(c.length - head, n - o);
            out.set(c.subarray(head, head + take), o);
            o += take;
            head = 0;
        }
        return out;
    }
    /** Remove and return the first n bytes; null if fewer buffered. */
    take(n) {
        const out = this.peek(n);
        if (out !== null)
            this.drop(n);
        return out;
    }
    /** Discard the first n bytes (caps at what is buffered). */
    drop(n) {
        let left = Math.min(n, this.size);
        this.size -= left;
        while (left > 0) {
            const avail = this.chunks[0].length - this.head;
            if (left < avail) {
                this.head += left;
                return;
            }
            left -= avail;
            this.chunks.shift();
            this.head = 0;
        }
    }
}

// ===== build/host/net.js =====
// net.send transport (README §13.6) + a request/response layer over it.
//
// net.send is "addressed unicast to a peer over its data channel" and is async
// by nature — it returns a correlation id and the host later delivers the
// response (§13.6). This module provides:
//   - Network:   the delivery fabric. LoopbackNetwork wires nodes in-process
//                for tests; a WebRTC/data-channel or TCP implementation (see
//                net-node.ts) satisfies the same interface in a real deployment.
//   - Transport: per-node request/response keyed by correlation id, plus the
//                bulk one-way frame path for content-addressed blocks (§13.6).
//
// Frames on the wire:
//   control req/res = [0|1 kind][corr u32 BE][type u8][payload ...]
//   bulk block.data = [2 kind][block_id 32][ciphertext ...]   (unsigned, §13.6)

const KIND_REQ = 0;
const KIND_RES = 1;
const KIND_BULK = 2;
/** In-process network for tests and single-process multi-node demos. Delivery
 *  is asynchronous (a microtask) to mirror a real data channel. A peer can be
 *  taken offline to model churn: frames to or from it are dropped, so the
 *  sender's request rejects and the cohort tips it toward Suspected/Lost. */
class LoopbackNetwork {
    sinks = new Map();
    offline = new Set();
    /** Total frames delivered — handy for asserting traffic in tests. */
    framesDelivered = 0;
    register(peerId, sink) {
        this.sinks.set(peerId, sink);
    }
    unregister(peerId) {
        this.sinks.delete(peerId);
    }
    setOnline(peerId, online) {
        if (online)
            this.offline.delete(peerId);
        else
            this.offline.add(peerId);
    }
    isOnline(peerId) {
        return this.sinks.has(peerId) && !this.offline.has(peerId);
    }
    send(from, to, frame) {
        if (this.offline.has(from) || this.offline.has(to))
            return; // dropped
        const sink = this.sinks.get(to);
        if (!sink)
            return;
        const copy = frame.slice();
        queueMicrotask(() => {
            if (this.offline.has(from) || this.offline.has(to))
                return;
            this.framesDelivered++;
            sink(from, copy);
        });
    }
}
/** Per-node request/response + bulk transport over a Network. */
class Transport {
    peerId;
    net;
    timeoutMs;
    corr = 1;
    pending = new Map();
    reqHandler = null;
    bulkHandler = null;
    constructor(peerId, net, 
    /** How long to wait for a response before treating the peer as unreachable
     *  (§13.6). Small in tests; a deployment tunes it against real latency. */
    timeoutMs = 200) {
        this.peerId = peerId;
        this.net = net;
        this.timeoutMs = timeoutMs;
        this.net.register(peerId, (from, frame) => this.onFrame(from, frame));
    }
    onRequest(handler) { this.reqHandler = handler; }
    onBulk(handler) { this.bulkHandler = handler; }
    /** Send a typed control request and await the typed response. Rejects on
     *  timeout (the peer is offline/unreachable). */
    request(to, type, payload) {
        const corr = this.corr++;
        const frame = new Uint8Array(1 + 4 + 1 + payload.length);
        frame[0] = KIND_REQ;
        writeU32BE(frame, 1, corr);
        frame[5] = type & 255;
        frame.set(payload, 6);
        return new Promise((resolve, reject) => {
            const timer = setTimeout(() => {
                this.pending.delete(corr);
                reject(new Error(`net.send: timeout to ${to.slice(0, 8)} (type ${type})`));
            }, this.timeoutMs);
            this.pending.set(corr, { to, resolve, reject, timer });
            this.net.send(this.peerId, to, frame);
        });
    }
    /** Scatter-gather: send the same typed request to many peers and gather the
     *  responses that arrive before the timeout. One entry per input peer (order
     *  preserved); an unreachable or timed-out peer comes back `ok:false` with no
     *  bytes (partial results, never a reject). This is the one concurrency a
     *  confined safe-js guest cannot do itself — `Promise.all` aborts the VM, so
     *  the fan-out lives host-side and the guest just consumes a finished list. */
    async requestMany(peers, type, payload) {
        return Promise.all(peers.map(async (peer) => {
            try {
                return { peer, ok: true, bytes: await this.request(peer, type, payload) };
            }
            catch {
                return { peer, ok: false, bytes: new Uint8Array(0) };
            }
        }));
    }
    /** Push a content-addressed block over the bulk plane — unsigned, the
     *  receiver verifies genesis_hash(bytes) == block_id itself (§13.6). */
    sendBulk(to, blockId, bytes) {
        const frame = new Uint8Array(1 + 32 + bytes.length);
        frame[0] = KIND_BULK;
        frame.set(blockId, 1);
        frame.set(bytes, 33);
        this.net.send(this.peerId, to, frame);
    }
    close() {
        for (const p of this.pending.values()) {
            clearTimeout(p.timer);
            p.reject(new Error("transport closed"));
        }
        this.pending.clear();
        this.net.unregister(this.peerId);
    }
    onFrame(from, frame) {
        const kind = frame[0];
        if (kind === KIND_BULK) {
            if (frame.length < 33 || !this.bulkHandler)
                return;
            this.bulkHandler(from, frame.slice(1, 33), frame.slice(33));
            return;
        }
        const corr = readU32BE(frame, 1);
        if (kind === KIND_RES) {
            const p = this.pending.get(corr);
            if (!p)
                return;
            // Bind the response to the request's target: a frame from anyone else is
            // dropped (the real response can still arrive before the timeout).
            if (p.to !== from)
                return;
            clearTimeout(p.timer);
            this.pending.delete(corr);
            p.resolve(frame.slice(6));
            return;
        }
        // KIND_REQ — dispatch to the node's handler and reply with the same corr.
        if (kind === KIND_REQ) {
            const type = frame[5];
            const payload = frame.slice(6);
            void this.dispatchRequest(from, corr, type, payload);
        }
    }
    async dispatchRequest(from, corr, type, payload) {
        let resp = null;
        if (this.reqHandler) {
            try {
                const r = this.reqHandler(from, type, payload);
                resp = r instanceof Promise ? await r : r;
            }
            catch {
                resp = null;
            }
        }
        const body = resp ?? new Uint8Array(0);
        const frame = new Uint8Array(6 + body.length);
        frame[0] = KIND_RES;
        writeU32BE(frame, 1, corr);
        frame[5] = type & 255;
        frame.set(body, 6);
        this.net.send(this.peerId, from, frame);
    }
}

// ===== build/host/net-link.js =====
// Channel identity binding (README §13.6). A real socket carries no trustworthy
// "from" field, so before a connection is allowed to deliver frames it runs a
// mutual challenge/response that proves each end holds the kernel private key
// for the public key it claims. From then on every frame is attributed to that
// authenticated identity — never to anything inside the frame. This is the
// node↔node analogue of chat-shell.js pinning each data-channel to a kernel pk
// and dropping envelopes signed by anyone else.
//
// PeerLink is transport-agnostic: it drives any RawChannel that delivers whole
// messages (TCP gets message framing from a length prefix; WebSocket already has
// message boundaries). Three short message types ride the channel:
//   HELLO = pubkey(32) ‖ nonce(32)         sent by both ends immediately
//   AUTH  = sign(transcript)(64)           binds both pubkeys + both nonces
//   FRAME = the opaque Network frame        only after both ends authenticate
//
// AUTH signs the whole transcript — DOMAIN ‖ the two (pubkey ‖ nonce) pairs in a
// canonical order — not just the peer's nonce. Signing the nonce alone would make a
// node a signing oracle: an attacker could relay a victim's outstanding nonce as its
// own HELLO, collect the node's signature, and replay it on another connection to
// impersonate the node. Binding both identities and both nonces ties every signature
// to the single exchange that produced it, so a harvested one verifies nowhere else.

const MSG_HELLO = 1, MSG_AUTH = 2, MSG_FRAME = 3;
const PK_LEN = 32, NONCE_LEN = 32, SIG_LEN = 64;
const DOMAIN = new TextEncoder().encode("seedkernel-channel-id-v1\0");
// Cap on frames buffered while the handshake completes. Sends past it drop the
// oldest — a peer that never authenticates cannot make us hoard memory.
const MAX_QUEUE = 256;
class PeerLink {
    weDialed;
    peerPubkey = null;
    peerId = "";
    authed = false;
    opts;
    ch;
    sodium;
    myNonce;
    queue = [];
    peerNonce = null;
    closed = false;
    constructor(opts) {
        this.opts = opts;
        this.ch = opts.channel;
        this.sodium = opts.sodium;
        this.weDialed = opts.weDialed;
        this.myNonce = opts.sodium.randombytes_buf(NONCE_LEN);
        this.ch.onMessage((m) => this.onMessage(m));
        this.ch.onClose(() => this.onChannelClose());
        this.sendHello();
    }
    /** Queue (pre-auth) or send (post-auth) a Network frame to this peer. */
    send(frame) {
        if (this.closed)
            return;
        if (this.authed) {
            this.ch.send(this.tag(MSG_FRAME, frame));
            return;
        }
        if (this.queue.length >= MAX_QUEUE)
            this.queue.shift();
        this.queue.push(frame);
    }
    close() {
        if (this.closed)
            return;
        this.closed = true;
        this.ch.close();
    }
    // ── handshake ────────────────────────────────────────────────────────────
    tag(type, payload) {
        const out = new Uint8Array(1 + payload.length);
        out[0] = type;
        out.set(payload, 1);
        return out;
    }
    sendHello() {
        const hello = new Uint8Array(PK_LEN + NONCE_LEN);
        hello.set(this.opts.identity.publicKey.subarray(0, PK_LEN), 0);
        hello.set(this.myNonce, PK_LEN);
        this.ch.send(this.tag(MSG_HELLO, hello));
    }
    /** The bytes both ends sign and verify: DOMAIN followed by each side's
     *  (pubkey ‖ nonce) block, the two ordered by their bytes so both ends derive an
     *  identical transcript regardless of who dialed. Requires peerPubkey/peerNonce. */
    transcript() {
        const mine = new Uint8Array(PK_LEN + NONCE_LEN);
        mine.set(this.opts.identity.publicKey.subarray(0, PK_LEN), 0);
        mine.set(this.myNonce, PK_LEN);
        const theirs = new Uint8Array(PK_LEN + NONCE_LEN);
        theirs.set(this.peerPubkey, 0);
        theirs.set(this.peerNonce, PK_LEN);
        const [lo, hi] = bytesCompare(mine, theirs) <= 0 ? [mine, theirs] : [theirs, mine];
        const msg = new Uint8Array(DOMAIN.length + lo.length + hi.length);
        msg.set(DOMAIN, 0);
        msg.set(lo, DOMAIN.length);
        msg.set(hi, DOMAIN.length + lo.length);
        return msg;
    }
    onMessage(m) {
        if (this.closed || m.length < 1)
            return;
        const type = m[0];
        const body = m.subarray(1);
        if (type === MSG_HELLO)
            this.onHello(body);
        else if (type === MSG_AUTH)
            this.onAuth(body);
        else if (type === MSG_FRAME) {
            if (this.authed)
                this.opts.onFrame(this.peerId, body.slice());
        }
    }
    onHello(body) {
        if (this.peerPubkey || body.length < PK_LEN + NONCE_LEN) {
            this.close();
            return;
        }
        const pubkey = body.slice(0, PK_LEN);
        const peerNonce = body.slice(PK_LEN, PK_LEN + NONCE_LEN);
        const peerId = toHex(pubkey);
        if (this.opts.expectPeerId && peerId !== this.opts.expectPeerId) {
            this.close();
            return;
        }
        this.peerPubkey = pubkey;
        this.peerNonce = peerNonce;
        this.peerId = peerId;
        // Authenticate over the full transcript — both pubkeys, both nonces — so this
        // signature is bound to this exchange and cannot be replayed on another.
        const sig = this.sodium.crypto_sign_detached(this.transcript(), this.opts.identity.privateKey);
        this.ch.send(this.tag(MSG_AUTH, sig));
    }
    onAuth(sig) {
        if (this.authed || !this.peerPubkey || !this.peerNonce || sig.length < SIG_LEN) {
            this.close();
            return;
        }
        let ok = false;
        try {
            ok = this.sodium.crypto_sign_verify_detached(sig.slice(0, SIG_LEN), this.transcript(), this.peerPubkey);
        }
        catch {
            ok = false;
        }
        if (!ok) {
            this.close();
            return;
        }
        this.authed = true;
        this.opts.onAuth(this.peerId, this);
        for (const f of this.queue)
            this.ch.send(this.tag(MSG_FRAME, f));
        this.queue.length = 0;
    }
    onChannelClose() {
        if (this.closed)
            return;
        this.closed = true;
        this.opts.onClose(this);
    }
}
/** Lexicographic compare of two byte arrays (-1 / 0 / 1). */
function bytesCompare(a, b) {
    const n = Math.min(a.length, b.length);
    for (let i = 0; i < n; i++) {
        if (a[i] !== b[i])
            return a[i] < b[i] ? -1 : 1;
    }
    return a.length === b.length ? 0 : (a.length < b.length ? -1 : 1);
}

// ===== build/host/net-route.js =====
// net-route.ts — the platform-agnostic routing core of a real Network (README
// §13.6). It owns NO sockets: links/connecting/inbound/addrs, the PeerLink
// handshake wiring, the deterministic double-connect rule, frame delivery and
// readiness all live here, and channel creation is injected as a ChannelFactory.
//
// This is the part net-node.ts promised was swappable — "PeerLink, the routing,
// and the handshake are untouched; the engine build swaps the native TCP binding
// behind the same RawChannel shape." net-node.ts supplies the node:net factory;
// the native (Go/wazero) loader supplies a factory over its __net primitive. The
// routing — and therefore the wire behaviour Go and Bun nodes must agree on — is
// the same code on every target.


class NodeNetworkCore {
    /** Diagnostics for tests, mirroring LoopbackNetwork. */
    framesDelivered = 0;
    framesSent = 0;
    /** Bound ports, valid after start() (ephemeral when requested with port 0). */
    port = 0;
    wsPort = 0;
    identity;
    sodium;
    channels;
    ownId;
    sink = null;
    links = new Map(); // authenticated, routable
    connecting = new Map(); // outbound, pre-auth
    inbound = new Set(); // accepted, pre-auth
    addrs = new Map(); // how to reach a peer
    authWaiters = new Set(); // ready() callers
    listenOpt;
    wsListenOpt;
    constructor(opts) {
        this.identity = opts.identity;
        this.sodium = opts.sodium;
        this.channels = opts.channels;
        this.ownId = toHex(opts.identity.publicKey);
        this.listenOpt = opts.listen;
        this.wsListenOpt = opts.wsListen;
    }
    // ── Network interface ──────────────────────────────────────────────────────
    register(peerId, sink) {
        if (peerId !== this.ownId)
            throw new Error("NodeNetwork is bound to one identity");
        this.sink = sink;
    }
    unregister(peerId) {
        if (peerId !== this.ownId)
            return;
        this.sink = null;
        this.close();
    }
    send(_from, to, frame) {
        if (to === this.ownId)
            return;
        this.framesSent++;
        const link = this.links.get(to) ?? this.connecting.get(to) ?? this.dial(to);
        if (link)
            link.send(frame);
        // No link and no address → silently dropped, exactly as LoopbackNetwork drops
        // a frame to an unknown peer; the Transport's timeout handles the fallout.
    }
    // ── teach the network how to reach a peer ──────────────────────────────────
    addPeerAddr(peerId, addr) {
        this.addrs.set(peerId, addr);
    }
    // ── lifecycle ──────────────────────────────────────────────────────────────
    /** Bind the configured listeners. Resolves once ports are known. */
    async start() {
        const { port, wsPort } = await this.channels.listen(this.listenOpt, this.wsListenOpt, (channel) => this.accept(channel));
        this.port = port;
        this.wsPort = wsPort;
    }
    /** Dial every known peer address and resolve once each is authenticated (or
     *  the deadline passes — links also form lazily on first send). Resolution is
     *  event-driven off promote(), not polled, so an all-up cohort resolves the
     *  moment its last handshake lands. */
    async ready(timeoutMs = 5000) {
        const targets = [...this.addrs.keys()].filter((p) => p !== this.ownId);
        for (const p of targets)
            if (!this.links.has(p))
                this.dial(p);
        const allUp = () => targets.every((p) => this.links.has(p));
        if (allUp())
            return;
        await new Promise((resolve) => {
            const done = () => { clearTimeout(timer); this.authWaiters.delete(check); resolve(); };
            const check = () => { if (allUp())
                done(); };
            const timer = setTimeout(done, timeoutMs);
            this.authWaiters.add(check);
        });
    }
    /** Tear down every connection and listener. */
    close() {
        for (const l of this.links.values())
            l.close();
        for (const l of this.connecting.values())
            l.close();
        for (const l of this.inbound)
            l.close();
        this.links.clear();
        this.connecting.clear();
        this.inbound.clear();
        this.channels.close();
    }
    // ── link management ────────────────────────────────────────────────────────
    dial(peerId) {
        const addr = this.addrs.get(peerId);
        if (!addr)
            return null;
        const channel = this.channels.connect(addr);
        const link = new PeerLink({
            channel, identity: this.identity, sodium: this.sodium,
            weDialed: true, expectPeerId: peerId,
            onAuth: (pid, l) => this.promote(pid, l),
            onFrame: (pid, frame) => this.deliver(pid, frame),
            onClose: (l) => this.forget(l),
        });
        this.connecting.set(peerId, link);
        return link;
    }
    accept(channel) {
        const link = new PeerLink({
            channel, identity: this.identity, sodium: this.sodium,
            weDialed: false,
            onAuth: (pid, l) => this.promote(pid, l),
            onFrame: (pid, frame) => this.deliver(pid, frame),
            onClose: (l) => this.forget(l),
        });
        this.inbound.add(link);
    }
    /** A link finished its handshake: install it as the routable link for its
     *  peer, resolving a double-connect by a rule both ends compute identically. */
    promote(peerId, link) {
        this.inbound.delete(link);
        if (this.connecting.get(peerId) === link)
            this.connecting.delete(peerId);
        const existing = this.links.get(peerId);
        if (existing && existing !== link) {
            // Two connections to the same peer (each dialed the other). Keep the one
            // whose *dialer* holds the smaller pubkey — a deterministic choice both
            // ends agree on, so exactly one survives.
            if (this.canonicalKeep(link)) {
                existing.close();
                this.links.set(peerId, link);
            }
            else {
                link.close();
            }
        }
        else {
            this.links.set(peerId, link);
        }
        for (const w of [...this.authWaiters])
            w();
    }
    canonicalKeep(link) {
        const peer = link.peerPubkey;
        const mine = this.identity.publicKey;
        const dialer = link.weDialed ? mine : peer;
        const smaller = bytesCompare(mine, peer) <= 0 ? mine : peer;
        return bytesCompare(dialer, smaller) === 0;
    }
    deliver(peerId, frame) {
        if (!this.sink || peerId === this.ownId)
            return;
        this.framesDelivered++;
        this.sink(peerId, frame);
    }
    forget(link) {
        this.inbound.delete(link);
        // Scan by value rather than keying off link.peerId: an outbound dial is
        // registered in `connecting` under the *target* peerId before the peer's
        // HELLO ever arrives (link.peerId is still ""), so a dial that dies pre-
        // handshake (ECONNREFUSED, expectPeerId mismatch) must still be removed —
        // otherwise send() returns the dead link forever and never redials.
        for (const [pid, l] of this.connecting)
            if (l === link)
                this.connecting.delete(pid);
        for (const [pid, l] of this.links)
            if (l === link)
                this.links.delete(pid);
    }
}
/** Parse a `--peers` entry: `<pubkeyhex>@<host>:<port>`. */
function parsePeerSpec(spec, transport) {
    const at = spec.indexOf("@");
    if (at < 0)
        throw new Error(`bad peer spec (want pk@host:port): ${spec}`);
    const peerId = spec.slice(0, at).toLowerCase();
    if (peerId.length !== 64 || /[^0-9a-f]/.test(peerId))
        throw new Error(`bad peer pubkey hex: ${spec}`);
    const hostPort = spec.slice(at + 1);
    const colon = hostPort.lastIndexOf(":");
    if (colon < 0)
        throw new Error(`bad peer host:port: ${spec}`);
    const host = hostPort.slice(0, colon);
    const port = Number(hostPort.slice(colon + 1));
    if (!Number.isInteger(port) || port <= 0)
        throw new Error(`bad peer port: ${spec}`);
    fromHex(peerId); // validate the pubkey is real hex by round-tripping (throws on garbage)
    return { peerId, addr: { host, port, transport } };
}

  globalThis["NodeNetworkCore"] = NodeNetworkCore;
  globalThis["Transport"] = Transport;
  globalThis["parsePeerSpec"] = parsePeerSpec;
  globalThis["toHex"] = toHex;
  globalThis["fromHex"] = fromHex;
})();
