"use strict";
// GENERATED by scripts/bundle-loader.mjs — do not edit.
(function () {

// ===== build/host/util.js =====
// Small byte helpers shared across the runtime host. No dependencies.
const HEX_BYTE = Array.from({ length: 256 }, (_, i) => i.toString(16).padStart(2, "0"));
function toHex(b) {
    const out = new Array(b.length);
    for (let i = 0; i < b.length; i++)
        out[i] = HEX_BYTE[b[i]];
    return out.join("");
}
function fromHex(hex) {
    const out = new Uint8Array(hex.length >> 1);
    for (let i = 0; i < out.length; i++)
        out[i] = parseInt(hex.substr(i * 2, 2), 16);
    return out;
}
function bytesEqual(a, b) {
    if (a.length !== b.length)
        return false;
    for (let i = 0; i < a.length; i++)
        if (a[i] !== b[i])
            return false;
    return true;
}
function concatBytes(parts) {
    let total = 0;
    for (const p of parts)
        total += p.length;
    const out = new Uint8Array(total);
    let o = 0;
    for (const p of parts) {
        out.set(p, o);
        o += p.length;
    }
    return out;
}
function writeU32BE(out, offset, value) {
    out[offset] = (value >>> 24) & 0xff;
    out[offset + 1] = (value >>> 16) & 0xff;
    out[offset + 2] = (value >>> 8) & 0xff;
    out[offset + 3] = value & 0xff;
}
function readU32BE(buf, offset) {
    return ((buf[offset] << 24) | (buf[offset + 1] << 16) |
        (buf[offset + 2] << 8) | buf[offset + 3]) >>> 0;
}
/** A FIFO of bytes fed in arbitrary chunks. Receive paths use it so that
 *  accumulating a large message stays O(n): chunks are appended by reference and
 *  bytes are copied exactly once, when a complete record is taken out — instead
 *  of re-copying the whole buffer on every incoming chunk. */
class ByteQueue {
    chunks = [];
    head = 0; // read offset into chunks[0]
    size = 0;
    get length() { return this.size; }
    push(chunk) {
        if (chunk.length === 0)
            return;
        this.chunks.push(chunk);
        this.size += chunk.length;
    }
    /** Copy of the first n bytes without consuming them; null if fewer buffered. */
    peek(n) {
        if (n > this.size)
            return null;
        const out = new Uint8Array(n);
        let o = 0, head = this.head;
        for (let i = 0; o < n; i++) {
            const c = this.chunks[i];
            const take = Math.min(c.length - head, n - o);
            out.set(c.subarray(head, head + take), o);
            o += take;
            head = 0;
        }
        return out;
    }
    /** Remove and return the first n bytes; null if fewer buffered. */
    take(n) {
        const out = this.peek(n);
        if (out !== null)
            this.drop(n);
        return out;
    }
    /** Discard the first n bytes (caps at what is buffered). */
    drop(n) {
        let left = Math.min(n, this.size);
        this.size -= left;
        while (left > 0) {
            const avail = this.chunks[0].length - this.head;
            if (left < avail) {
                this.head += left;
                return;
            }
            left -= avail;
            this.chunks.shift();
            this.head = 0;
        }
    }
}

// ===== build/host/net-link.js =====
// Channel identity binding (README §13.6). A real socket carries no trustworthy
// "from" field, so before a connection is allowed to deliver frames it runs a
// mutual challenge/response that proves each end holds the kernel private key
// for the public key it claims. From then on every frame is attributed to that
// authenticated identity — never to anything inside the frame. This is the
// node↔node analogue of chat-shell.js pinning each data-channel to a kernel pk
// and dropping envelopes signed by anyone else.
//
// PeerLink is transport-agnostic: it drives any RawChannel that delivers whole
// messages (TCP gets message framing from a length prefix; WebSocket already has
// message boundaries). Three short message types ride the channel:
//   HELLO = pubkey(32) ‖ nonce(32)         sent by both ends immediately
//   AUTH  = sign(transcript)(64)           binds both pubkeys + both nonces
//   FRAME = the opaque Network frame        only after both ends authenticate
//
// AUTH signs the whole transcript — DOMAIN ‖ the two (pubkey ‖ nonce) pairs in a
// canonical order — not just the peer's nonce. Signing the nonce alone would make a
// node a signing oracle: an attacker could relay a victim's outstanding nonce as its
// own HELLO, collect the node's signature, and replay it on another connection to
// impersonate the node. Binding both identities and both nonces ties every signature
// to the single exchange that produced it, so a harvested one verifies nowhere else.

const MSG_HELLO = 1, MSG_AUTH = 2, MSG_FRAME = 3;
const PK_LEN = 32, NONCE_LEN = 32, SIG_LEN = 64;
const DOMAIN = new TextEncoder().encode("seedkernel-channel-id-v1\0");
// Cap on frames buffered while the handshake completes. Sends past it drop the
// oldest — a peer that never authenticates cannot make us hoard memory.
const MAX_QUEUE = 256;
class PeerLink {
    weDialed;
    peerPubkey = null;
    peerId = "";
    authed = false;
    opts;
    ch;
    sodium;
    myNonce;
    queue = [];
    peerNonce = null;
    closed = false;
    constructor(opts) {
        this.opts = opts;
        this.ch = opts.channel;
        this.sodium = opts.sodium;
        this.weDialed = opts.weDialed;
        this.myNonce = opts.sodium.randombytes_buf(NONCE_LEN);
        this.ch.onMessage((m) => this.onMessage(m));
        this.ch.onClose(() => this.onChannelClose());
        this.sendHello();
    }
    /** Queue (pre-auth) or send (post-auth) a Network frame to this peer. */
    send(frame) {
        if (this.closed)
            return;
        if (this.authed) {
            this.ch.send(this.tag(MSG_FRAME, frame));
            return;
        }
        if (this.queue.length >= MAX_QUEUE)
            this.queue.shift();
        this.queue.push(frame);
    }
    close() {
        if (this.closed)
            return;
        this.closed = true;
        this.ch.close();
    }
    // ── handshake ────────────────────────────────────────────────────────────
    tag(type, payload) {
        const out = new Uint8Array(1 + payload.length);
        out[0] = type;
        out.set(payload, 1);
        return out;
    }
    sendHello() {
        const hello = new Uint8Array(PK_LEN + NONCE_LEN);
        hello.set(this.opts.identity.publicKey.subarray(0, PK_LEN), 0);
        hello.set(this.myNonce, PK_LEN);
        this.ch.send(this.tag(MSG_HELLO, hello));
    }
    /** The bytes both ends sign and verify: DOMAIN followed by each side's
     *  (pubkey ‖ nonce) block, the two ordered by their bytes so both ends derive an
     *  identical transcript regardless of who dialed. Requires peerPubkey/peerNonce. */
    transcript() {
        const mine = new Uint8Array(PK_LEN + NONCE_LEN);
        mine.set(this.opts.identity.publicKey.subarray(0, PK_LEN), 0);
        mine.set(this.myNonce, PK_LEN);
        const theirs = new Uint8Array(PK_LEN + NONCE_LEN);
        theirs.set(this.peerPubkey, 0);
        theirs.set(this.peerNonce, PK_LEN);
        const [lo, hi] = bytesCompare(mine, theirs) <= 0 ? [mine, theirs] : [theirs, mine];
        const msg = new Uint8Array(DOMAIN.length + lo.length + hi.length);
        msg.set(DOMAIN, 0);
        msg.set(lo, DOMAIN.length);
        msg.set(hi, DOMAIN.length + lo.length);
        return msg;
    }
    onMessage(m) {
        if (this.closed || m.length < 1)
            return;
        const type = m[0];
        const body = m.subarray(1);
        if (type === MSG_HELLO)
            this.onHello(body);
        else if (type === MSG_AUTH)
            this.onAuth(body);
        else if (type === MSG_FRAME) {
            if (this.authed)
                this.opts.onFrame(this.peerId, body.slice());
        }
    }
    onHello(body) {
        if (this.peerPubkey || body.length < PK_LEN + NONCE_LEN) {
            this.close();
            return;
        }
        const pubkey = body.slice(0, PK_LEN);
        const peerNonce = body.slice(PK_LEN, PK_LEN + NONCE_LEN);
        const peerId = toHex(pubkey);
        if (this.opts.expectPeerId && peerId !== this.opts.expectPeerId) {
            this.close();
            return;
        }
        this.peerPubkey = pubkey;
        this.peerNonce = peerNonce;
        this.peerId = peerId;
        // Authenticate over the full transcript — both pubkeys, both nonces — so this
        // signature is bound to this exchange and cannot be replayed on another.
        const sig = this.sodium.crypto_sign_detached(this.transcript(), this.opts.identity.privateKey);
        this.ch.send(this.tag(MSG_AUTH, sig));
    }
    onAuth(sig) {
        if (this.authed || !this.peerPubkey || !this.peerNonce || sig.length < SIG_LEN) {
            this.close();
            return;
        }
        let ok = false;
        try {
            ok = this.sodium.crypto_sign_verify_detached(sig.slice(0, SIG_LEN), this.transcript(), this.peerPubkey);
        }
        catch {
            ok = false;
        }
        if (!ok) {
            this.close();
            return;
        }
        this.authed = true;
        this.opts.onAuth(this.peerId, this);
        for (const f of this.queue)
            this.ch.send(this.tag(MSG_FRAME, f));
        this.queue.length = 0;
    }
    onChannelClose() {
        if (this.closed)
            return;
        this.closed = true;
        this.opts.onClose(this);
    }
}
/** Lexicographic compare of two byte arrays (-1 / 0 / 1). */
function bytesCompare(a, b) {
    const n = Math.min(a.length, b.length);
    for (let i = 0; i < n; i++) {
        if (a[i] !== b[i])
            return a[i] < b[i] ? -1 : 1;
    }
    return a.length === b.length ? 0 : (a.length < b.length ? -1 : 1);
}

  globalThis["PeerLink"] = PeerLink;
  globalThis["bytesCompare"] = bytesCompare;
  globalThis["toHex"] = toHex;
  globalThis["fromHex"] = fromHex;
})();
